package br.ufrj.dcc.arq.modelo;

public class MemoriaControle {
	
	public void decodificaEChama(int cod) {
		switch(cod) {
			case   0: { MicroInstrucoes.halt(); break; }
			case   1: { MicroInstrucoes.addImedR0(); break; }
			case   2: { MicroInstrucoes.addImedR1(); break; }
			case   3: { MicroInstrucoes.addImedR2(); break; }
			case   4: { MicroInstrucoes.addImedR3(); break; }
			case   5: { MicroInstrucoes.addImedR4(); break; }
			case   6: { MicroInstrucoes.addImedER0(); break; }
			case   7: { MicroInstrucoes.addImedER1(); break; }
			case   8: { MicroInstrucoes.addImedER2(); break; }
			case   9: { MicroInstrucoes.addImedER3(); break; }
			case  10: { MicroInstrucoes.addImedER4(); break; }
			case  11: { MicroInstrucoes.addR0R0(); break; }
			case  12: { MicroInstrucoes.addR0R1(); break; }
			case  13: { MicroInstrucoes.addR0R2(); break; }
			case  14: { MicroInstrucoes.addR0R3(); break; }
			case  15: { MicroInstrucoes.addR0R4(); break; }
			case  16: { MicroInstrucoes.addR1R0(); break; }
			case  17: { MicroInstrucoes.addR1R1(); break; }
			case  18: { MicroInstrucoes.addR1R2(); break; }
			case  19: { MicroInstrucoes.addR1R3(); break; }
			case  20: { MicroInstrucoes.addR1R4(); break; }
			case  21: { MicroInstrucoes.addR2R0(); break; }
			case  22: { MicroInstrucoes.addR2R1(); break; }
			case  23: { MicroInstrucoes.addR2R2(); break; }
			case  24: { MicroInstrucoes.addR2R3(); break; }
			case  25: { MicroInstrucoes.addR2R4(); break; }
			case  26: { MicroInstrucoes.addR3R0(); break; }
			case  27: { MicroInstrucoes.addR3R1(); break; }
			case  28: { MicroInstrucoes.addR3R2(); break; }
			case  29: { MicroInstrucoes.addR3R3(); break; }
			case  30: { MicroInstrucoes.addR3R4(); break; }
			case  31: { MicroInstrucoes.addR4R0(); break; }
			case  32: { MicroInstrucoes.addR4R1(); break; }
			case  33: { MicroInstrucoes.addR4R2(); break; }
			case  34: { MicroInstrucoes.addR4R3(); break; }
			case  35: { MicroInstrucoes.addR4R4(); break; }
			case  36: { MicroInstrucoes.halt(); break; }
			case  37: { MicroInstrucoes.halt(); break; }
			case  38: { MicroInstrucoes.halt(); break; }
			case  39: { MicroInstrucoes.halt(); break; }
			case  40: { MicroInstrucoes.halt(); break; }
			case  41: { MicroInstrucoes.halt(); break; }
			case  42: { MicroInstrucoes.halt(); break; }
			case  43: { MicroInstrucoes.halt(); break; }
			case  44: { MicroInstrucoes.halt(); break; }
			case  45: { MicroInstrucoes.halt(); break; }
			case  46: { MicroInstrucoes.halt(); break; }
			case  47: { MicroInstrucoes.halt(); break; }
			case  48: { MicroInstrucoes.halt(); break; }
			case  49: { MicroInstrucoes.halt(); break; }
			case  50: { MicroInstrucoes.halt(); break; }
			case  51: { MicroInstrucoes.halt(); break; }
			case  52: { MicroInstrucoes.halt(); break; }
			case  53: { MicroInstrucoes.halt(); break; }
			case  54: { MicroInstrucoes.halt(); break; }
			case  55: { MicroInstrucoes.halt(); break; }
			case  56: { MicroInstrucoes.halt(); break; }
			case  57: { MicroInstrucoes.halt(); break; }
			case  58: { MicroInstrucoes.halt(); break; }
			case  59: { MicroInstrucoes.halt(); break; }
			case  60: { MicroInstrucoes.halt(); break; }
			case  61: { MicroInstrucoes.halt(); break; }
			case  62: { MicroInstrucoes.halt(); break; }
			case  63: { MicroInstrucoes.halt(); break; }
			case  64: { MicroInstrucoes.halt(); break; }
			case  65: { MicroInstrucoes.halt(); break; }
			case  66: { MicroInstrucoes.halt(); break; }
			case  67: { MicroInstrucoes.halt(); break; }
			case  68: { MicroInstrucoes.halt(); break; }
			case  69: { MicroInstrucoes.halt(); break; }
			case  70: { MicroInstrucoes.halt(); break; }
			case  71: { MicroInstrucoes.halt(); break; }
			case  72: { MicroInstrucoes.halt(); break; }
			case  73: { MicroInstrucoes.halt(); break; }
			case  74: { MicroInstrucoes.halt(); break; }
			case  75: { MicroInstrucoes.halt(); break; }
			case  76: { MicroInstrucoes.halt(); break; }
			case  77: { MicroInstrucoes.halt(); break; }
			case  78: { MicroInstrucoes.halt(); break; }
			case  79: { MicroInstrucoes.halt(); break; }
			case  80: { MicroInstrucoes.halt(); break; }
			case  81: { MicroInstrucoes.halt(); break; }
			case  82: { MicroInstrucoes.halt(); break; }
			case  83: { MicroInstrucoes.halt(); break; }
			case  84: { MicroInstrucoes.halt(); break; }
			case  85: { MicroInstrucoes.halt(); break; }
			case  86: { MicroInstrucoes.halt(); break; }
			case  87: { MicroInstrucoes.halt(); break; }
			case  88: { MicroInstrucoes.halt(); break; }
			case  89: { MicroInstrucoes.halt(); break; }
			case  90: { MicroInstrucoes.halt(); break; }
			case  91: { MicroInstrucoes.halt(); break; }
			case  92: { MicroInstrucoes.halt(); break; }
			case  93: { MicroInstrucoes.halt(); break; }
			case  94: { MicroInstrucoes.halt(); break; }
			case  95: { MicroInstrucoes.halt(); break; }
			case  96: { MicroInstrucoes.halt(); break; }
			case  97: { MicroInstrucoes.halt(); break; }
			case  98: { MicroInstrucoes.halt(); break; }
			case  99: { MicroInstrucoes.halt(); break; }
			case 100: { MicroInstrucoes.halt(); break; }
			case 101: { MicroInstrucoes.halt(); break; }
			case 102: { MicroInstrucoes.halt(); break; }
			case 103: { MicroInstrucoes.halt(); break; }
			case 104: { MicroInstrucoes.halt(); break; }
			case 105: { MicroInstrucoes.halt(); break; }
			case 106: { MicroInstrucoes.halt(); break; }
			case 107: { MicroInstrucoes.halt(); break; }
			case 108: { MicroInstrucoes.halt(); break; }
			case 109: { MicroInstrucoes.halt(); break; }
			case 110: { MicroInstrucoes.halt(); break; }
			case 111: { MicroInstrucoes.halt(); break; }
			case 112: { MicroInstrucoes.halt(); break; }
			case 113: { MicroInstrucoes.halt(); break; }
			case 114: { MicroInstrucoes.halt(); break; }
			case 115: { MicroInstrucoes.halt(); break; }
			case 116: { MicroInstrucoes.halt(); break; }
			case 117: { MicroInstrucoes.halt(); break; }
			case 118: { MicroInstrucoes.halt(); break; }
			case 119: { MicroInstrucoes.halt(); break; }
			case 120: { MicroInstrucoes.halt(); break; }
			case 121: { MicroInstrucoes.halt(); break; }
			case 122: { MicroInstrucoes.halt(); break; }
			case 123: { MicroInstrucoes.halt(); break; }
			case 124: { MicroInstrucoes.halt(); break; }
			case 125: { MicroInstrucoes.halt(); break; }
			case 126: { MicroInstrucoes.halt(); break; }
			case 127: { MicroInstrucoes.halt(); break; }
			case 128: { MicroInstrucoes.halt(); break; }
			case 129: { MicroInstrucoes.halt(); break; }
			case 130: { MicroInstrucoes.halt(); break; }
			case 131: { MicroInstrucoes.halt(); break; }
			case 132: { MicroInstrucoes.halt(); break; }
			case 133: { MicroInstrucoes.halt(); break; }
			case 134: { MicroInstrucoes.halt(); break; }
			case 135: { MicroInstrucoes.halt(); break; }
			case 136: { MicroInstrucoes.halt(); break; }
			case 137: { MicroInstrucoes.halt(); break; }
			case 138: { MicroInstrucoes.halt(); break; }
			case 139: { MicroInstrucoes.halt(); break; }
			case 140: { MicroInstrucoes.halt(); break; }
			case 141: { MicroInstrucoes.halt(); break; }
			case 142: { MicroInstrucoes.halt(); break; }
			case 143: { MicroInstrucoes.halt(); break; }
			case 144: { MicroInstrucoes.halt(); break; }
			case 145: { MicroInstrucoes.halt(); break; }
			case 146: { MicroInstrucoes.halt(); break; }
			case 147: { MicroInstrucoes.halt(); break; }
			case 148: { MicroInstrucoes.halt(); break; }
			case 149: { MicroInstrucoes.halt(); break; }
			case 150: { MicroInstrucoes.halt(); break; }
			case 151: { MicroInstrucoes.halt(); break; }
			case 152: { MicroInstrucoes.halt(); break; }
			case 153: { MicroInstrucoes.halt(); break; }
			case 154: { MicroInstrucoes.halt(); break; }
			case 155: { MicroInstrucoes.halt(); break; }
			case 156: { MicroInstrucoes.halt(); break; }
			case 157: { MicroInstrucoes.halt(); break; }
			case 158: { MicroInstrucoes.halt(); break; }
			case 159: { MicroInstrucoes.halt(); break; }
			case 160: { MicroInstrucoes.halt(); break; }
			case 161: { MicroInstrucoes.halt(); break; }
			case 162: { MicroInstrucoes.halt(); break; }
			case 163: { MicroInstrucoes.halt(); break; }
			case 164: { MicroInstrucoes.halt(); break; }
			case 165: { MicroInstrucoes.halt(); break; }
			case 166: { MicroInstrucoes.halt(); break; }
			case 167: { MicroInstrucoes.halt(); break; }
			case 168: { MicroInstrucoes.halt(); break; }
			case 169: { MicroInstrucoes.halt(); break; }
			case 170: { MicroInstrucoes.halt(); break; }
			case 171: { MicroInstrucoes.halt(); break; }
			case 172: { MicroInstrucoes.halt(); break; }
			case 173: { MicroInstrucoes.halt(); break; }
			case 174: { MicroInstrucoes.halt(); break; }
			case 175: { MicroInstrucoes.halt(); break; }
			case 176: { MicroInstrucoes.halt(); break; }
			case 177: { MicroInstrucoes.halt(); break; }
			case 178: { MicroInstrucoes.halt(); break; }
			case 179: { MicroInstrucoes.halt(); break; }
			case 180: { MicroInstrucoes.halt(); break; }
			case 181: { MicroInstrucoes.halt(); break; }
			case 182: { MicroInstrucoes.halt(); break; }
			case 183: { MicroInstrucoes.halt(); break; }
			case 184: { MicroInstrucoes.halt(); break; }
			case 185: { MicroInstrucoes.halt(); break; }
			case 186: { MicroInstrucoes.halt(); break; }
			case 187: { MicroInstrucoes.halt(); break; }
			case 188: { MicroInstrucoes.halt(); break; }
			case 189: { MicroInstrucoes.halt(); break; }
			case 190: { MicroInstrucoes.halt(); break; }
			case 191: { MicroInstrucoes.halt(); break; }
			case 192: { MicroInstrucoes.halt(); break; }
			case 193: { MicroInstrucoes.halt(); break; }
			case 194: { MicroInstrucoes.halt(); break; }
			case 195: { MicroInstrucoes.halt(); break; }
			case 196: { MicroInstrucoes.halt(); break; }
			case 197: { MicroInstrucoes.halt(); break; }
			case 198: { MicroInstrucoes.halt(); break; }
			case 199: { MicroInstrucoes.halt(); break; }
			case 200: { MicroInstrucoes.halt(); break; }
			case 201: { MicroInstrucoes.halt(); break; }
			case 202: { MicroInstrucoes.halt(); break; }
			case 203: { MicroInstrucoes.halt(); break; }
			case 204: { MicroInstrucoes.halt(); break; }
			case 205: { MicroInstrucoes.halt(); break; }
			case 206: { MicroInstrucoes.halt(); break; }
			case 207: { MicroInstrucoes.halt(); break; }
			case 208: { MicroInstrucoes.halt(); break; }
			case 209: { MicroInstrucoes.halt(); break; }
			case 210: { MicroInstrucoes.halt(); break; }
			case 211: { MicroInstrucoes.halt(); break; }
			case 212: { MicroInstrucoes.halt(); break; }
			case 213: { MicroInstrucoes.halt(); break; }
			case 214: { MicroInstrucoes.halt(); break; }
			case 215: { MicroInstrucoes.halt(); break; }
			case 216: { MicroInstrucoes.halt(); break; }
			case 217: { MicroInstrucoes.halt(); break; }
			case 218: { MicroInstrucoes.halt(); break; }
			case 219: { MicroInstrucoes.halt(); break; }
			case 220: { MicroInstrucoes.halt(); break; }
			case 221: { MicroInstrucoes.halt(); break; }
			case 222: { MicroInstrucoes.halt(); break; }
			case 223: { MicroInstrucoes.halt(); break; }
			case 224: { MicroInstrucoes.halt(); break; }
			case 225: { MicroInstrucoes.halt(); break; }
			case 226: { MicroInstrucoes.halt(); break; }
			case 227: { MicroInstrucoes.halt(); break; }
			case 228: { MicroInstrucoes.halt(); break; }
			case 229: { MicroInstrucoes.halt(); break; }
			case 230: { MicroInstrucoes.halt(); break; }
			case 231: { MicroInstrucoes.halt(); break; }
			case 232: { MicroInstrucoes.halt(); break; }
			case 233: { MicroInstrucoes.halt(); break; }
			case 234: { MicroInstrucoes.halt(); break; }
			case 235: { MicroInstrucoes.halt(); break; }
			case 236: { MicroInstrucoes.halt(); break; }
			case 237: { MicroInstrucoes.halt(); break; }
			case 238: { MicroInstrucoes.halt(); break; }
			case 239: { MicroInstrucoes.halt(); break; }
			case 240: { MicroInstrucoes.halt(); break; }
			case 241: { MicroInstrucoes.halt(); break; }
			case 242: { MicroInstrucoes.halt(); break; }
			case 243: { MicroInstrucoes.halt(); break; }
			case 244: { MicroInstrucoes.halt(); break; }
			case 245: { MicroInstrucoes.halt(); break; }
			case 246: { MicroInstrucoes.halt(); break; }
			case 247: { MicroInstrucoes.halt(); break; }
			case 248: { MicroInstrucoes.halt(); break; }
			case 249: { MicroInstrucoes.halt(); break; }
			case 250: { MicroInstrucoes.halt(); break; }
			case 251: { MicroInstrucoes.halt(); break; }
			case 252: { MicroInstrucoes.halt(); break; }
			case 253: { MicroInstrucoes.halt(); break; }
			case 254: { MicroInstrucoes.halt(); break; }
			case 255: { MicroInstrucoes.halt(); break; }
			case 256: { MicroInstrucoes.halt(); break; }
			case 257: { MicroInstrucoes.halt(); break; }
			case 258: { MicroInstrucoes.halt(); break; }
			case 259: { MicroInstrucoes.halt(); break; }
			case 260: { MicroInstrucoes.halt(); break; }
			case 261: { MicroInstrucoes.halt(); break; }
			case 262: { MicroInstrucoes.halt(); break; }
			case 263: { MicroInstrucoes.halt(); break; }
			case 264: { MicroInstrucoes.halt(); break; }
			case 265: { MicroInstrucoes.halt(); break; }
			case 266: { MicroInstrucoes.halt(); break; }
			case 267: { MicroInstrucoes.halt(); break; }
			case 268: { MicroInstrucoes.halt(); break; }
			case 269: { MicroInstrucoes.halt(); break; }
			case 270: { MicroInstrucoes.halt(); break; }
			case 271: { MicroInstrucoes.halt(); break; }
			case 272: { MicroInstrucoes.halt(); break; }
			case 273: { MicroInstrucoes.halt(); break; }
			case 274: { MicroInstrucoes.halt(); break; }
			case 275: { MicroInstrucoes.halt(); break; }
			case 276: { MicroInstrucoes.halt(); break; }
			case 277: { MicroInstrucoes.halt(); break; }
			case 278: { MicroInstrucoes.halt(); break; }
			case 279: { MicroInstrucoes.halt(); break; }
			case 280: { MicroInstrucoes.halt(); break; }
			case 281: { MicroInstrucoes.halt(); break; }
			case 282: { MicroInstrucoes.halt(); break; }
			case 283: { MicroInstrucoes.halt(); break; }
			case 284: { MicroInstrucoes.halt(); break; }
			case 285: { MicroInstrucoes.halt(); break; }
			case 286: { MicroInstrucoes.halt(); break; }
			case 287: { MicroInstrucoes.halt(); break; }
			case 288: { MicroInstrucoes.halt(); break; }
			case 289: { MicroInstrucoes.halt(); break; }
			case 290: { MicroInstrucoes.halt(); break; }
			case 291: { MicroInstrucoes.halt(); break; }
			case 292: { MicroInstrucoes.halt(); break; }
			case 293: { MicroInstrucoes.halt(); break; }
			case 294: { MicroInstrucoes.halt(); break; }
			case 295: { MicroInstrucoes.halt(); break; }
			case 296: { MicroInstrucoes.halt(); break; }
			case 297: { MicroInstrucoes.halt(); break; }
			case 298: { MicroInstrucoes.halt(); break; }
			case 299: { MicroInstrucoes.halt(); break; }
			case 300: { MicroInstrucoes.halt(); break; }
			case 301: { MicroInstrucoes.halt(); break; }
			case 302: { MicroInstrucoes.halt(); break; }
			case 303: { MicroInstrucoes.halt(); break; }
			case 304: { MicroInstrucoes.halt(); break; }
			case 305: { MicroInstrucoes.halt(); break; }
			case 306: { MicroInstrucoes.halt(); break; }
			case 307: { MicroInstrucoes.halt(); break; }
			case 308: { MicroInstrucoes.halt(); break; }
			case 309: { MicroInstrucoes.halt(); break; }
			case 310: { MicroInstrucoes.halt(); break; }
			case 311: { MicroInstrucoes.halt(); break; }
			case 312: { MicroInstrucoes.halt(); break; }
			case 313: { MicroInstrucoes.halt(); break; }
			case 314: { MicroInstrucoes.halt(); break; }
			case 315: { MicroInstrucoes.halt(); break; }
			case 316: { MicroInstrucoes.halt(); break; }
			case 317: { MicroInstrucoes.halt(); break; }
			case 318: { MicroInstrucoes.halt(); break; }
			case 319: { MicroInstrucoes.halt(); break; }
			case 320: { MicroInstrucoes.halt(); break; }
			case 321: { MicroInstrucoes.halt(); break; }
			case 322: { MicroInstrucoes.halt(); break; }
			case 323: { MicroInstrucoes.halt(); break; }
			case 324: { MicroInstrucoes.halt(); break; }
			case 325: { MicroInstrucoes.halt(); break; }
			case 326: { MicroInstrucoes.halt(); break; }
			case 327: { MicroInstrucoes.halt(); break; }
			case 328: { MicroInstrucoes.halt(); break; }
			case 329: { MicroInstrucoes.halt(); break; }
			case 330: { MicroInstrucoes.halt(); break; }
			case 331: { MicroInstrucoes.halt(); break; }
			case 332: { MicroInstrucoes.halt(); break; }
			case 333: { MicroInstrucoes.halt(); break; }
			case 334: { MicroInstrucoes.halt(); break; }
			case 335: { MicroInstrucoes.halt(); break; }
			case 336: { MicroInstrucoes.halt(); break; }
			case 337: { MicroInstrucoes.halt(); break; }
			case 338: { MicroInstrucoes.halt(); break; }
			case 339: { MicroInstrucoes.halt(); break; }
			case 340: { MicroInstrucoes.halt(); break; }
			case 341: { MicroInstrucoes.halt(); break; }
			case 342: { MicroInstrucoes.halt(); break; }
			case 343: { MicroInstrucoes.halt(); break; }
			case 344: { MicroInstrucoes.halt(); break; }
			case 345: { MicroInstrucoes.halt(); break; }
			case 346: { MicroInstrucoes.halt(); break; }
			case 347: { MicroInstrucoes.halt(); break; }
			case 348: { MicroInstrucoes.halt(); break; }
			case 349: { MicroInstrucoes.halt(); break; }
			case 350: { MicroInstrucoes.halt(); break; }
			case 351: { MicroInstrucoes.halt(); break; }
			case 352: { MicroInstrucoes.halt(); break; }
			case 353: { MicroInstrucoes.halt(); break; }
			case 354: { MicroInstrucoes.halt(); break; }
			case 355: { MicroInstrucoes.halt(); break; }
			case 356: { MicroInstrucoes.halt(); break; }
			case 357: { MicroInstrucoes.halt(); break; }
			case 358: { MicroInstrucoes.halt(); break; }
			case 359: { MicroInstrucoes.halt(); break; }
			case 360: { MicroInstrucoes.halt(); break; }
			case 361: { MicroInstrucoes.halt(); break; }
			case 362: { MicroInstrucoes.halt(); break; }
			case 363: { MicroInstrucoes.halt(); break; }
			case 364: { MicroInstrucoes.halt(); break; }
			case 365: { MicroInstrucoes.halt(); break; }
			case 366: { MicroInstrucoes.halt(); break; }
			case 367: { MicroInstrucoes.halt(); break; }
			case 368: { MicroInstrucoes.halt(); break; }
			case 369: { MicroInstrucoes.halt(); break; }
			case 370: { MicroInstrucoes.halt(); break; }
			case 371: { MicroInstrucoes.halt(); break; }
			case 372: { MicroInstrucoes.halt(); break; }
			case 373: { MicroInstrucoes.halt(); break; }
			case 374: { MicroInstrucoes.halt(); break; }
			case 375: { MicroInstrucoes.halt(); break; }
			case 376: { MicroInstrucoes.halt(); break; }
			case 377: { MicroInstrucoes.halt(); break; }
			case 378: { MicroInstrucoes.halt(); break; }
			case 379: { MicroInstrucoes.halt(); break; }
			case 380: { MicroInstrucoes.halt(); break; }
			case 381: { MicroInstrucoes.halt(); break; }
			case 382: { MicroInstrucoes.halt(); break; }
			case 383: { MicroInstrucoes.halt(); break; }
			case 384: { MicroInstrucoes.halt(); break; }
			case 385: { MicroInstrucoes.halt(); break; }
			case 386: { MicroInstrucoes.halt(); break; }
			case 387: { MicroInstrucoes.halt(); break; }
			case 388: { MicroInstrucoes.halt(); break; }
			case 389: { MicroInstrucoes.halt(); break; }
			case 390: { MicroInstrucoes.halt(); break; }
			case 391: { MicroInstrucoes.halt(); break; }
			case 392: { MicroInstrucoes.halt(); break; }
			case 393: { MicroInstrucoes.halt(); break; }
			case 394: { MicroInstrucoes.halt(); break; }
			case 395: { MicroInstrucoes.halt(); break; }
			case 396: { MicroInstrucoes.halt(); break; }
			case 397: { MicroInstrucoes.halt(); break; }
			case 398: { MicroInstrucoes.halt(); break; }
			case 399: { MicroInstrucoes.halt(); break; }
			case 400: { MicroInstrucoes.halt(); break; }
			case 401: { MicroInstrucoes.halt(); break; }
			case 402: { MicroInstrucoes.halt(); break; }
			case 403: { MicroInstrucoes.halt(); break; }
			case 404: { MicroInstrucoes.halt(); break; }
			case 405: { MicroInstrucoes.halt(); break; }
			case 406: { MicroInstrucoes.halt(); break; }
			case 407: { MicroInstrucoes.halt(); break; }
			case 408: { MicroInstrucoes.halt(); break; }
			case 409: { MicroInstrucoes.halt(); break; }
			case 410: { MicroInstrucoes.halt(); break; }
			case 411: { MicroInstrucoes.halt(); break; }
			case 412: { MicroInstrucoes.halt(); break; }
			case 413: { MicroInstrucoes.halt(); break; }
			case 414: { MicroInstrucoes.halt(); break; }
			case 415: { MicroInstrucoes.halt(); break; }
			case 416: { MicroInstrucoes.halt(); break; }
			case 417: { MicroInstrucoes.halt(); break; }
			case 418: { MicroInstrucoes.halt(); break; }
			case 419: { MicroInstrucoes.halt(); break; }
			case 420: { MicroInstrucoes.halt(); break; }
			case 421: { MicroInstrucoes.halt(); break; }
			case 422: { MicroInstrucoes.halt(); break; }
			case 423: { MicroInstrucoes.halt(); break; }
			case 424: { MicroInstrucoes.halt(); break; }
			case 425: { MicroInstrucoes.halt(); break; }
			case 426: { MicroInstrucoes.halt(); break; }
			case 427: { MicroInstrucoes.halt(); break; }
			case 428: { MicroInstrucoes.halt(); break; }
			case 429: { MicroInstrucoes.halt(); break; }
			case 430: { MicroInstrucoes.halt(); break; }
			case 431: { MicroInstrucoes.halt(); break; }
			case 432: { MicroInstrucoes.halt(); break; }
			case 433: { MicroInstrucoes.halt(); break; }
			case 434: { MicroInstrucoes.halt(); break; }
			case 435: { MicroInstrucoes.halt(); break; }
			case 436: { MicroInstrucoes.halt(); break; }
			case 437: { MicroInstrucoes.halt(); break; }
			case 438: { MicroInstrucoes.halt(); break; }
			case 439: { MicroInstrucoes.halt(); break; }
			case 440: { MicroInstrucoes.halt(); break; }
			case 441: { MicroInstrucoes.halt(); break; }
			case 442: { MicroInstrucoes.halt(); break; }
			case 443: { MicroInstrucoes.halt(); break; }
			case 444: { MicroInstrucoes.halt(); break; }
			case 445: { MicroInstrucoes.halt(); break; }
			case 446: { MicroInstrucoes.halt(); break; }
			case 447: { MicroInstrucoes.halt(); break; }
			case 448: { MicroInstrucoes.halt(); break; }
			case 449: { MicroInstrucoes.halt(); break; }
			case 450: { MicroInstrucoes.halt(); break; }
			case 451: { MicroInstrucoes.halt(); break; }
			case 452: { MicroInstrucoes.halt(); break; }
			case 453: { MicroInstrucoes.halt(); break; }
			case 454: { MicroInstrucoes.halt(); break; }
			case 455: { MicroInstrucoes.halt(); break; }
			case 456: { MicroInstrucoes.halt(); break; }
			case 457: { MicroInstrucoes.halt(); break; }
			case 458: { MicroInstrucoes.halt(); break; }
			case 459: { MicroInstrucoes.halt(); break; }
			case 460: { MicroInstrucoes.halt(); break; }
			case 461: { MicroInstrucoes.halt(); break; }
			case 462: { MicroInstrucoes.halt(); break; }
			case 463: { MicroInstrucoes.halt(); break; }
			case 464: { MicroInstrucoes.halt(); break; }
			case 465: { MicroInstrucoes.halt(); break; }
			case 466: { MicroInstrucoes.halt(); break; }
			case 467: { MicroInstrucoes.halt(); break; }
			case 468: { MicroInstrucoes.halt(); break; }
			case 469: { MicroInstrucoes.halt(); break; }
			case 470: { MicroInstrucoes.halt(); break; }
			case 471: { MicroInstrucoes.halt(); break; }
			case 472: { MicroInstrucoes.halt(); break; }
			case 473: { MicroInstrucoes.halt(); break; }
			case 474: { MicroInstrucoes.halt(); break; }
			case 475: { MicroInstrucoes.halt(); break; }
			case 476: { MicroInstrucoes.halt(); break; }
			case 477: { MicroInstrucoes.halt(); break; }
			case 478: { MicroInstrucoes.halt(); break; }
			case 479: { MicroInstrucoes.halt(); break; }
			case 480: { MicroInstrucoes.halt(); break; }
			case 481: { MicroInstrucoes.halt(); break; }
			case 482: { MicroInstrucoes.halt(); break; }
			case 483: { MicroInstrucoes.halt(); break; }
			case 484: { MicroInstrucoes.halt(); break; }
			case 485: { MicroInstrucoes.halt(); break; }
			case 486: { MicroInstrucoes.halt(); break; }
			case 487: { MicroInstrucoes.halt(); break; }
			case 488: { MicroInstrucoes.halt(); break; }
			case 489: { MicroInstrucoes.halt(); break; }
			case 490: { MicroInstrucoes.halt(); break; }
			case 491: { MicroInstrucoes.halt(); break; }
			case 492: { MicroInstrucoes.halt(); break; }
			case 493: { MicroInstrucoes.halt(); break; }
			case 494: { MicroInstrucoes.halt(); break; }
			case 495: { MicroInstrucoes.halt(); break; }
			case 496: { MicroInstrucoes.halt(); break; }
			case 497: { MicroInstrucoes.halt(); break; }
			case 498: { MicroInstrucoes.halt(); break; }
			case 499: { MicroInstrucoes.halt(); break; }
			case 500: { MicroInstrucoes.halt(); break; }
			case 501: { MicroInstrucoes.halt(); break; }
			case 502: { MicroInstrucoes.halt(); break; }
			case 503: { MicroInstrucoes.halt(); break; }
			case 504: { MicroInstrucoes.halt(); break; }
			case 505: { MicroInstrucoes.halt(); break; }
			case 506: { MicroInstrucoes.halt(); break; }
			case 507: { MicroInstrucoes.halt(); break; }
			case 508: { MicroInstrucoes.halt(); break; }
			case 509: { MicroInstrucoes.halt(); break; }
			case 510: { MicroInstrucoes.halt(); break; }
			case 511: { MicroInstrucoes.halt(); break; }
			case 512: { MicroInstrucoes.halt(); break; }
			case 513: { MicroInstrucoes.halt(); break; }
			case 514: { MicroInstrucoes.halt(); break; }
			case 515: { MicroInstrucoes.halt(); break; }
			case 516: { MicroInstrucoes.halt(); break; }
			case 517: { MicroInstrucoes.halt(); break; }
			case 518: { MicroInstrucoes.halt(); break; }
			case 519: { MicroInstrucoes.halt(); break; }
			case 520: { MicroInstrucoes.halt(); break; }
			case 521: { MicroInstrucoes.halt(); break; }
			case 522: { MicroInstrucoes.halt(); break; }
			case 523: { MicroInstrucoes.halt(); break; }
			case 524: { MicroInstrucoes.halt(); break; }
			case 525: { MicroInstrucoes.halt(); break; }
			case 526: { MicroInstrucoes.halt(); break; }
			case 527: { MicroInstrucoes.halt(); break; }
			case 528: { MicroInstrucoes.halt(); break; }
			case 529: { MicroInstrucoes.halt(); break; }
			case 530: { MicroInstrucoes.halt(); break; }
			case 531: { MicroInstrucoes.halt(); break; }
			case 532: { MicroInstrucoes.halt(); break; }
			case 533: { MicroInstrucoes.halt(); break; }
			case 534: { MicroInstrucoes.halt(); break; }
			case 535: { MicroInstrucoes.halt(); break; }
			case 536: { MicroInstrucoes.halt(); break; }
			case 537: { MicroInstrucoes.halt(); break; }
			case 538: { MicroInstrucoes.halt(); break; }
			case 539: { MicroInstrucoes.halt(); break; }
			case 540: { MicroInstrucoes.halt(); break; }
			case 541: { MicroInstrucoes.halt(); break; }
			case 542: { MicroInstrucoes.halt(); break; }
			case 543: { MicroInstrucoes.halt(); break; }
			case 544: { MicroInstrucoes.halt(); break; }
			case 545: { MicroInstrucoes.halt(); break; }
			case 546: { MicroInstrucoes.halt(); break; }
			case 547: { MicroInstrucoes.halt(); break; }
			case 548: { MicroInstrucoes.halt(); break; }
			case 549: { MicroInstrucoes.halt(); break; }
			case 550: { MicroInstrucoes.halt(); break; }
			case 551: { MicroInstrucoes.halt(); break; }
			case 552: { MicroInstrucoes.halt(); break; }
			case 553: { MicroInstrucoes.halt(); break; }
			case 554: { MicroInstrucoes.halt(); break; }
			case 555: { MicroInstrucoes.halt(); break; }
			case 556: { MicroInstrucoes.halt(); break; }
			case 557: { MicroInstrucoes.halt(); break; }
			case 558: { MicroInstrucoes.halt(); break; }
			case 559: { MicroInstrucoes.halt(); break; }
			case 560: { MicroInstrucoes.halt(); break; }
			case 561: { MicroInstrucoes.halt(); break; }
			case 562: { MicroInstrucoes.halt(); break; }
			case 563: { MicroInstrucoes.halt(); break; }
			case 564: { MicroInstrucoes.halt(); break; }
			case 565: { MicroInstrucoes.halt(); break; }
			case 566: { MicroInstrucoes.halt(); break; }
			case 567: { MicroInstrucoes.halt(); break; }
			case 568: { MicroInstrucoes.halt(); break; }
			case 569: { MicroInstrucoes.halt(); break; }
			case 570: { MicroInstrucoes.halt(); break; }
			case 571: { MicroInstrucoes.halt(); break; }
			case 572: { MicroInstrucoes.halt(); break; }
			case 573: { MicroInstrucoes.halt(); break; }
			case 574: { MicroInstrucoes.halt(); break; }
			case 575: { MicroInstrucoes.halt(); break; }
			case 576: { MicroInstrucoes.halt(); break; }
			case 577: { MicroInstrucoes.halt(); break; }
			case 578: { MicroInstrucoes.halt(); break; }
			case 579: { MicroInstrucoes.halt(); break; }
			case 580: { MicroInstrucoes.halt(); break; }
			case 581: { MicroInstrucoes.halt(); break; }
			case 582: { MicroInstrucoes.halt(); break; }
			case 583: { MicroInstrucoes.halt(); break; }
			case 584: { MicroInstrucoes.halt(); break; }
			case 585: { MicroInstrucoes.halt(); break; }
			case 586: { MicroInstrucoes.halt(); break; }
			case 587: { MicroInstrucoes.halt(); break; }
			case 588: { MicroInstrucoes.halt(); break; }
			case 589: { MicroInstrucoes.halt(); break; }
			case 590: { MicroInstrucoes.halt(); break; }
			case 591: { MicroInstrucoes.halt(); break; }
			case 592: { MicroInstrucoes.halt(); break; }
			case 593: { MicroInstrucoes.halt(); break; }
			case 594: { MicroInstrucoes.halt(); break; }
			case 595: { MicroInstrucoes.halt(); break; }
			case 596: { MicroInstrucoes.halt(); break; }
			case 597: { MicroInstrucoes.halt(); break; }
			case 598: { MicroInstrucoes.halt(); break; }
			case 599: { MicroInstrucoes.halt(); break; }
			case 600: { MicroInstrucoes.halt(); break; }
			case 601: { MicroInstrucoes.halt(); break; }
			case 602: { MicroInstrucoes.halt(); break; }
			case 603: { MicroInstrucoes.halt(); break; }
			case 604: { MicroInstrucoes.halt(); break; }
			case 605: { MicroInstrucoes.halt(); break; }
			case 606: { MicroInstrucoes.halt(); break; }
			case 607: { MicroInstrucoes.halt(); break; }
			case 608: { MicroInstrucoes.halt(); break; }
			case 609: { MicroInstrucoes.halt(); break; }
			case 610: { MicroInstrucoes.halt(); break; }
			case 611: { MicroInstrucoes.halt(); break; }
			case 612: { MicroInstrucoes.halt(); break; }
			case 613: { MicroInstrucoes.halt(); break; }
			case 614: { MicroInstrucoes.halt(); break; }
			case 615: { MicroInstrucoes.halt(); break; }
			case 616: { MicroInstrucoes.halt(); break; }
			case 617: { MicroInstrucoes.halt(); break; }
			case 618: { MicroInstrucoes.halt(); break; }
			case 619: { MicroInstrucoes.halt(); break; }
			case 620: { MicroInstrucoes.halt(); break; }
			case 621: { MicroInstrucoes.halt(); break; }
			case 622: { MicroInstrucoes.halt(); break; }
			case 623: { MicroInstrucoes.halt(); break; }
			case 624: { MicroInstrucoes.halt(); break; }
			case 625: { MicroInstrucoes.halt(); break; }
			case 626: { MicroInstrucoes.halt(); break; }
			case 627: { MicroInstrucoes.halt(); break; }
			case 628: { MicroInstrucoes.halt(); break; }
			case 629: { MicroInstrucoes.halt(); break; }
			case 630: { MicroInstrucoes.halt(); break; }
			case 631: { MicroInstrucoes.halt(); break; }
			case 632: { MicroInstrucoes.halt(); break; }
			case 633: { MicroInstrucoes.halt(); break; }
			case 634: { MicroInstrucoes.halt(); break; }
			case 635: { MicroInstrucoes.halt(); break; }
			case 636: { MicroInstrucoes.halt(); break; }
			case 637: { MicroInstrucoes.halt(); break; }
			case 638: { MicroInstrucoes.halt(); break; }
			case 639: { MicroInstrucoes.halt(); break; }
			case 640: { MicroInstrucoes.halt(); break; }
			case 641: { MicroInstrucoes.halt(); break; }
			case 642: { MicroInstrucoes.halt(); break; }
			case 643: { MicroInstrucoes.halt(); break; }
			case 644: { MicroInstrucoes.halt(); break; }
			case 645: { MicroInstrucoes.halt(); break; }
			case 646: { MicroInstrucoes.halt(); break; }
			case 647: { MicroInstrucoes.halt(); break; }
			case 648: { MicroInstrucoes.halt(); break; }
			case 649: { MicroInstrucoes.halt(); break; }
			case 650: { MicroInstrucoes.halt(); break; }
			case 651: { MicroInstrucoes.halt(); break; }
			case 652: { MicroInstrucoes.halt(); break; }
			case 653: { MicroInstrucoes.halt(); break; }
			case 654: { MicroInstrucoes.halt(); break; }
			case 655: { MicroInstrucoes.halt(); break; }
			case 656: { MicroInstrucoes.halt(); break; }
			case 657: { MicroInstrucoes.halt(); break; }
			case 658: { MicroInstrucoes.halt(); break; }
			case 659: { MicroInstrucoes.halt(); break; }
			case 660: { MicroInstrucoes.halt(); break; }
			case 661: { MicroInstrucoes.halt(); break; }
			case 662: { MicroInstrucoes.halt(); break; }
			case 663: { MicroInstrucoes.halt(); break; }
			case 664: { MicroInstrucoes.halt(); break; }
			case 665: { MicroInstrucoes.halt(); break; }
			case 666: { MicroInstrucoes.halt(); break; }
			case 667: { MicroInstrucoes.halt(); break; }
			case 668: { MicroInstrucoes.halt(); break; }
			case 669: { MicroInstrucoes.halt(); break; }
			case 670: { MicroInstrucoes.halt(); break; }
			case 671: { MicroInstrucoes.halt(); break; }
			case 672: { MicroInstrucoes.halt(); break; }
			case 673: { MicroInstrucoes.halt(); break; }
			case 674: { MicroInstrucoes.halt(); break; }
			case 675: { MicroInstrucoes.halt(); break; }
			case 676: { MicroInstrucoes.halt(); break; }
			case 677: { MicroInstrucoes.halt(); break; }
			case 678: { MicroInstrucoes.halt(); break; }
			case 679: { MicroInstrucoes.halt(); break; }
			case 680: { MicroInstrucoes.halt(); break; }
			case 681: { MicroInstrucoes.halt(); break; }
			case 682: { MicroInstrucoes.halt(); break; }
			case 683: { MicroInstrucoes.halt(); break; }
			case 684: { MicroInstrucoes.halt(); break; }
			case 685: { MicroInstrucoes.halt(); break; }
			case 686: { MicroInstrucoes.halt(); break; }
			case 687: { MicroInstrucoes.halt(); break; }
			case 688: { MicroInstrucoes.halt(); break; }
			case 689: { MicroInstrucoes.halt(); break; }
			case 690: { MicroInstrucoes.halt(); break; }
			case 691: { MicroInstrucoes.halt(); break; }
			case 692: { MicroInstrucoes.halt(); break; }
			case 693: { MicroInstrucoes.halt(); break; }
			case 694: { MicroInstrucoes.halt(); break; }
			case 695: { MicroInstrucoes.halt(); break; }
			case 696: { MicroInstrucoes.halt(); break; }
			case 697: { MicroInstrucoes.halt(); break; }
			case 698: { MicroInstrucoes.halt(); break; }
			case 699: { MicroInstrucoes.halt(); break; }
			case 700: { MicroInstrucoes.halt(); break; }
			case 701: { MicroInstrucoes.halt(); break; }
			case 702: { MicroInstrucoes.halt(); break; }
			case 703: { MicroInstrucoes.halt(); break; }
			case 704: { MicroInstrucoes.halt(); break; }
			case 705: { MicroInstrucoes.halt(); break; }
			case 706: { MicroInstrucoes.halt(); break; }
			case 707: { MicroInstrucoes.halt(); break; }
			case 708: { MicroInstrucoes.halt(); break; }
			case 709: { MicroInstrucoes.halt(); break; }
			case 710: { MicroInstrucoes.halt(); break; }
			case 711: { MicroInstrucoes.halt(); break; }
			case 712: { MicroInstrucoes.halt(); break; }
			case 713: { MicroInstrucoes.halt(); break; }
			case 714: { MicroInstrucoes.halt(); break; }
			case 715: { MicroInstrucoes.halt(); break; }
			case 716: { MicroInstrucoes.halt(); break; }
			case 717: { MicroInstrucoes.halt(); break; }
		}
	}
	
}
